import type { Metadata } from 'next';
import './globals.css';
import SanityProvider from '@/components/SanityProvider';
import { AdminSidebar } from '@/components/Sidebar';
import { Geist } from 'next/font/google';
import { cn } from '@/lib/utils';
import { Toaster } from '@street-culture/ui';

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

export const metadata: Metadata = {
  title: {
    default: 'Street Culture',
    template: '%s | Street Culture',
  },
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn('h-full', 'antialiased', 'font-sans', "font-sans", geist.variable)}
    >
      <body className="min-h-full grid grid-cols-[200px_1fr] relative">
        <SanityProvider>
          <AdminSidebar />
          {children}
        </SanityProvider>
      </body>
    </html>
  );
}
