import type { Metadata } from 'next';
import './globals.css';
import SanityProvider from '@/components/SanityProvider';

export const metadata: Metadata = {
  title: {
    default: 'Street Culture',
    template: '%s | Street Culture',
  },
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={` h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <SanityProvider>{children}</SanityProvider>
      </body>
    </html>
  );
}
