/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: ../admin/src/sanity/schema.json
export type SizeChart = {
  _id: string;
  _type: 'sizeChart';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  measurementDesc?: Array<{
    label?: LocaleString;
    body?: LocaleText;
    _key: string;
  }>;
  sizes?: Array<{
    label?: string;
    measurements?: Array<
      {
        _key: string;
      } & Measurement
    >;
    _key: string;
  }>;
  image?: ImageWithAlt;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
};

export type ImageWithAlt = {
  _type: 'imageWithAlt';
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
};

export type LocaleText = {
  _type: 'localeText';
  en?: string;
  ko?: string;
};

export type LocaleString = {
  _type: 'localeString';
  en?: string;
  ko?: string;
};

export type Slug = {
  _type: 'slug';
  current?: string;
  source?: string;
};

export type Measurement = {
  _type: 'measurement';
  label?:
    | 'shoulder'
    | 'chest'
    | 'length'
    | 'sleeve'
    | 'waist'
    | 'hips'
    | 'inseam'
    | 'rise'
    | 'bottom-opening'
    | 'neck-opening'
    | 'bicep'
    | 'deck-width'
    | 'deck-ength'
    | 'wheel-base';
  value?: string;
};

export type ProductContentReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'productContent';
};

export type ShopTheLook = {
  _id: string;
  _type: 'shopTheLook';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  image?: ImageWithAlt;
  hotspots?: Array<{
    x?: number;
    y?: number;
    product?: ProductContentReference;
    _key: string;
  }>;
};

export type Hero = {
  _id: string;
  _type: 'hero';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  banners?: Array<{
    title?: LocaleString;
    text?: LocaleString;
    image?: ImageWithAlt;
    position?: 'left' | 'right';
    _key: string;
  }>;
};

export type SiteSetting = {
  _id: string;
  _type: 'siteSetting';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  siteName?: string;
  primaryLogo?: ImageWithAlt;
  secondaryLogo?: ImageWithAlt;
  socialLinks?: Array<
    {
      _key: string;
    } & SocialLink
  >;
  navigation?: Array<
    | {
        label?: LocaleString;
        href?: string;
        isButton?: boolean;
        _type: 'navLink';
        _key: string;
      }
    | {
        label?: LocaleString;
        dropdownItems?: Array<{
          label?: LocaleString;
          href?: string;
          isButton?: boolean;
          _type: 'dropdownItem';
          _key: string;
        }>;
        _type: 'navDropdown';
        _key: string;
      }
  >;
  footerDescription?: LocaleString;
  footerColumns?: Array<{
    title?: LocaleString;
    columnLinks?: Array<{
      label?: LocaleString;
      href?: string;
      _type: 'columnLink';
      _key: string;
    }>;
    _type: 'footerColumn';
    _key: string;
  }>;
};

export type Lookbook = {
  _id: string;
  _type: 'lookbook';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  images?: Array<
    {
      _key: string;
    } & ImageWithAlt
  >;
  body?: LocaleText;
  products?: Array<{
    name?: string;
    displayTitle?: LocaleString;
    body?: LocaleText;
    images?: Array<
      {
        _key: string;
      } & ImageWithAlt
    >;
    colorCode?: Color;
    _type: 'productContent';
    _key: string;
  }>;
};

export type ProductContent = {
  _id: string;
  _type: 'productContent';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  displayTitle?: LocaleString;
  body?: LocaleText;
  images?: Array<
    {
      _key: string;
    } & ImageWithAlt
  >;
  colorCode?: Color;
};

export type Color = {
  _type: 'color';
  hex?: string;
  rgba?: string;
  hsl?: string;
  isGradient?: boolean;
  hex2?: string;
  angle?: number;
  css?: string;
};

export type Store = {
  _id: string;
  _type: 'store';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  email?: string;
  phone?: string;
  street?: string;
  city?: string;
  state?: string;
  zip?: string;
  country?: string;
  latitude?: number;
  longitude?: number;
  body?: string;
  image?: ImageWithAlt;
  storeHours?: Array<{
    day?: number;
    openingHours?: string;
    closingHours?: string;
    _key: string;
  }>;
};

export type OurStory = {
  _id: string;
  _type: 'ourStory';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  year?: number;
  title?: LocaleString;
  body?: LocaleText;
};

export type UtilityPage = {
  _id: string;
  _type: 'utilityPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  title?: LocaleString;
  body?: LocaleText;
};

export type Faqs = {
  _id: string;
  _type: 'faqs';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  faqs?: Array<
    {
      _key: string;
    } & Faq
  >;
};

export type AuthorReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'author';
};

export type BlogCategoryReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'blogCategory';
};

export type Blog = {
  _id: string;
  _type: 'blog';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  author?: AuthorReference;
  category?: BlogCategoryReference;
  minRead?: number;
  publishedAt?: string;
  excerpt?: LocaleString;
  body?: LocaleText;
  image?: ImageWithAlt;
  seo?: Seo;
  isFeatured?: boolean;
  comments?: Array<{
    user?: string;
    commentedAt?: string;
    body?: string;
    _key: string;
  }>;
  isMemberOnly?: boolean;
};

export type Seo = {
  _type: 'seo';
  metaTitle?: LocaleString;
  metaDescription?: LocaleString;
  ogImage?: ImageWithAlt;
  noIndex?: boolean;
};

export type BlogCategory = {
  _id: string;
  _type: 'blogCategory';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
};

export type Author = {
  _id: string;
  _type: 'author';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  body?: LocaleText;
  image?: ImageWithAlt;
  socialLink?: string;
};

export type VideoEmbeded = {
  _type: 'videoEmbeded';
  url?: string;
  caption?: string;
};

export type Faq = {
  _type: 'faq';
  title?: LocaleString;
  body?: LocaleText;
};

export type SocialLink = {
  _type: 'socialLink';
  platform?:
    'facebook' | 'instagram' | 'youtube' | 'linkedin' | 'github' | 'twitterx';
  url?: string;
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: 'span';
        _key: string;
      }>;
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
      listItem?: 'bullet' | 'number';
      markDefs?: Array<{
        href?: string;
        _type: 'link';
        _key: string;
      }>;
      level?: number;
      _type: 'block';
      _key: string;
    }
  | ({
      _key: string;
    } & ImageWithAlt)
>;

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type MediaTag = {
  _id: string;
  _type: 'media.tag';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: Slug;
};

export type BlockStyles = {
  _type: 'blockStyles';
  padding?: {
    top?:
      | '0'
      | '4px'
      | '8px'
      | '12px'
      | '16px'
      | '20px'
      | '24px'
      | '32px'
      | '40px'
      | '48px'
      | '56px'
      | '64px'
      | '80px';
    right?:
      | '0'
      | '4px'
      | '8px'
      | '12px'
      | '16px'
      | '20px'
      | '24px'
      | '32px'
      | '40px'
      | '48px'
      | '56px'
      | '64px'
      | '80px';
    bottom?:
      | '0'
      | '4px'
      | '8px'
      | '12px'
      | '16px'
      | '20px'
      | '24px'
      | '32px'
      | '40px'
      | '48px'
      | '56px'
      | '64px'
      | '80px';
    left?:
      | '0'
      | '4px'
      | '8px'
      | '12px'
      | '16px'
      | '20px'
      | '24px'
      | '32px'
      | '40px'
      | '48px'
      | '56px'
      | '64px'
      | '80px';
    topMd?:
      | '0'
      | '4px'
      | '8px'
      | '12px'
      | '16px'
      | '20px'
      | '24px'
      | '32px'
      | '40px'
      | '48px'
      | '56px'
      | '64px'
      | '80px';
    rightMd?:
      | '0'
      | '4px'
      | '8px'
      | '12px'
      | '16px'
      | '20px'
      | '24px'
      | '32px'
      | '40px'
      | '48px'
      | '56px'
      | '64px'
      | '80px';
    bottomMd?:
      | '0'
      | '4px'
      | '8px'
      | '12px'
      | '16px'
      | '20px'
      | '24px'
      | '32px'
      | '40px'
      | '48px'
      | '56px'
      | '64px'
      | '80px';
    leftMd?:
      | '0'
      | '4px'
      | '8px'
      | '12px'
      | '16px'
      | '20px'
      | '24px'
      | '32px'
      | '40px'
      | '48px'
      | '56px'
      | '64px'
      | '80px';
    topLg?:
      | '0'
      | '4px'
      | '8px'
      | '12px'
      | '16px'
      | '20px'
      | '24px'
      | '32px'
      | '40px'
      | '48px'
      | '56px'
      | '64px'
      | '80px';
    rightLg?:
      | '0'
      | '4px'
      | '8px'
      | '12px'
      | '16px'
      | '20px'
      | '24px'
      | '32px'
      | '40px'
      | '48px'
      | '56px'
      | '64px'
      | '80px';
    bottomLg?:
      | '0'
      | '4px'
      | '8px'
      | '12px'
      | '16px'
      | '20px'
      | '24px'
      | '32px'
      | '40px'
      | '48px'
      | '56px'
      | '64px'
      | '80px';
    leftLg?:
      | '0'
      | '4px'
      | '8px'
      | '12px'
      | '16px'
      | '20px'
      | '24px'
      | '32px'
      | '40px'
      | '48px'
      | '56px'
      | '64px'
      | '80px';
  };
  margin?: {
    top?:
      | '0'
      | '4px'
      | '8px'
      | '12px'
      | '16px'
      | '20px'
      | '24px'
      | '32px'
      | '40px'
      | '48px'
      | '56px'
      | '64px'
      | '80px';
    right?:
      | '0'
      | '4px'
      | '8px'
      | '12px'
      | '16px'
      | '20px'
      | '24px'
      | '32px'
      | '40px'
      | '48px'
      | '56px'
      | '64px'
      | '80px';
    bottom?:
      | '0'
      | '4px'
      | '8px'
      | '12px'
      | '16px'
      | '20px'
      | '24px'
      | '32px'
      | '40px'
      | '48px'
      | '56px'
      | '64px'
      | '80px';
    left?:
      | '0'
      | '4px'
      | '8px'
      | '12px'
      | '16px'
      | '20px'
      | '24px'
      | '32px'
      | '40px'
      | '48px'
      | '56px'
      | '64px'
      | '80px';
    topMd?:
      | '0'
      | '4px'
      | '8px'
      | '12px'
      | '16px'
      | '20px'
      | '24px'
      | '32px'
      | '40px'
      | '48px'
      | '56px'
      | '64px'
      | '80px';
    rightMd?:
      | '0'
      | '4px'
      | '8px'
      | '12px'
      | '16px'
      | '20px'
      | '24px'
      | '32px'
      | '40px'
      | '48px'
      | '56px'
      | '64px'
      | '80px';
    bottomMd?:
      | '0'
      | '4px'
      | '8px'
      | '12px'
      | '16px'
      | '20px'
      | '24px'
      | '32px'
      | '40px'
      | '48px'
      | '56px'
      | '64px'
      | '80px';
    leftMd?:
      | '0'
      | '4px'
      | '8px'
      | '12px'
      | '16px'
      | '20px'
      | '24px'
      | '32px'
      | '40px'
      | '48px'
      | '56px'
      | '64px'
      | '80px';
    topLg?:
      | '0'
      | '4px'
      | '8px'
      | '12px'
      | '16px'
      | '20px'
      | '24px'
      | '32px'
      | '40px'
      | '48px'
      | '56px'
      | '64px'
      | '80px';
    rightLg?:
      | '0'
      | '4px'
      | '8px'
      | '12px'
      | '16px'
      | '20px'
      | '24px'
      | '32px'
      | '40px'
      | '48px'
      | '56px'
      | '64px'
      | '80px';
    bottomLg?:
      | '0'
      | '4px'
      | '8px'
      | '12px'
      | '16px'
      | '20px'
      | '24px'
      | '32px'
      | '40px'
      | '48px'
      | '56px'
      | '64px'
      | '80px';
    leftLg?:
      | '0'
      | '4px'
      | '8px'
      | '12px'
      | '16px'
      | '20px'
      | '24px'
      | '32px'
      | '40px'
      | '48px'
      | '56px'
      | '64px'
      | '80px';
  };
  border?: {
    width?: string;
    style?: string;
    color?: string;
  };
  borderRadius?: {
    topLeft?: string;
    topRight?: string;
    bottomRight?: string;
    bottomLeft?: string;
  };
  background?: {
    color?: string;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: 'image';
    };
    size?: 'cover' | 'contain' | 'auto';
    overlay?: string;
  };
  typography?: {
    textAlign?: string;
    fontSize?: string;
    textColor?: string;
  };
  effects?: {
    shadow?: string;
    opacity?: number;
    overflow?: string;
  };
};

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SizeChart
  | SanityImageAssetReference
  | ImageWithAlt
  | LocaleText
  | LocaleString
  | Slug
  | Measurement
  | ProductContentReference
  | ShopTheLook
  | Hero
  | SiteSetting
  | Lookbook
  | ProductContent
  | Color
  | Store
  | OurStory
  | UtilityPage
  | Faqs
  | AuthorReference
  | BlogCategoryReference
  | Blog
  | Seo
  | BlogCategory
  | Author
  | VideoEmbeded
  | Faq
  | SocialLink
  | BlockContent
  | SanityImageCrop
  | SanityImageHotspot
  | MediaTag
  | BlockStyles
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../admin/src/features/authors/queries.ts
// Variable: ALL_AUTHORS
// Query: *[_type == 'author' && defined(slug.current)]{  _id,  name,  "slug": slug.current,  "imageUrl": coalesce(image.asset->url),  "imageAlt": coalesce(image.alt) }
export type ALL_AUTHORS_RESULT = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  imageUrl: string | null;
  imageAlt: string | null;
}>;

// Source: ../admin/src/features/authors/queries.ts
// Variable: AUTHOR
// Query: *[_type == 'author' && slug.current == $slug][0]{  _id,  name,  "slug": slug.current,  "bioEn": coalesce(body.en, ''),  "bioKo": coalesce(body.ko, ''),  "imageUrl": coalesce(image.asset->url, ''),  "imageAlt": coalesce(image.alt, ''),  socialLink,  "blogs": *[_type == 'blog'            && defined(slug.current)            && references(^._id)]            | order(publishedAt){              name,              "slug": slug.current,              "imageUrl": image.asset->url,              "imageAlt": image.alt,              publishedAt,              "excerptEn": excerpt.en,              "excerptKo": excerpt.ko            } }
export type AUTHOR_RESULT = {
  _id: string;
  name: string | null;
  slug: string | null;
  bioEn: string | '';
  bioKo: string | '';
  imageUrl: string | '';
  imageAlt: string | '';
  socialLink: string | null;
  blogs: Array<{
    name: string | null;
    slug: string | null;
    imageUrl: string | null;
    imageAlt: string | null;
    publishedAt: string | null;
    excerptEn: string | null;
    excerptKo: string | null;
  }>;
} | null;

// Source: ../admin/src/features/our-stories/queries.ts
// Variable: ALL_STORIES_QUERY
// Query: *[_type == 'ourStory'  && defined(slug.current)]  |order(year){  _id,  name,  "slug": slug.current,  year,  "titleEn": coalesce(title.en, ''),  "titleKo": coalesce(title.ko, ''),  "bodyEn": coalesce(body.en, ''),  "bodyKo": coalesce(body.ko, ''), }
export type ALL_STORIES_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  year: number | null;
  titleEn: string | '';
  titleKo: string | '';
  bodyEn: string | '';
  bodyKo: string | '';
}>;

// Source: ../admin/src/features/our-stories/queries.ts
// Variable: STORY_QUERY
// Query: *[_type == 'ourStory'  && slug.current == $slug][0]{  _id,  name,  "slug": slug.current,  year,  "titleEn": coalesce(title.en, ''),  "titleKo": coalesce(title.ko, ''),  "bodyEn": coalesce(body.en, ''),  "bodyKo": coalesce(body.ko, ''), }
export type STORY_QUERY_RESULT = {
  _id: string;
  name: string | null;
  slug: string | null;
  year: number | null;
  titleEn: string | '';
  titleKo: string | '';
  bodyEn: string | '';
  bodyKo: string | '';
} | null;

// Query TypeMap
import '@sanity/client';
declare module '@sanity/client' {
  interface SanityQueries {
    '*[_type == \'author\'\n && defined(slug.current)]{\n  _id,\n  name,\n  "slug": slug.current,\n  "imageUrl": coalesce(image.asset->url),\n  "imageAlt": coalesce(image.alt)\n }': ALL_AUTHORS_RESULT;
    '*[_type == \'author\'\n && slug.current == $slug][0]{\n  _id,\n  name,\n  "slug": slug.current,\n  "bioEn": coalesce(body.en, \'\'),\n  "bioKo": coalesce(body.ko, \'\'),\n  "imageUrl": coalesce(image.asset->url, \'\'),\n  "imageAlt": coalesce(image.alt, \'\'),\n  socialLink,\n  "blogs": *[_type == \'blog\'\n            && defined(slug.current)\n            && references(^._id)]\n            | order(publishedAt){\n              name,\n              "slug": slug.current,\n              "imageUrl": image.asset->url,\n              "imageAlt": image.alt,\n              publishedAt,\n              "excerptEn": excerpt.en,\n              "excerptKo": excerpt.ko\n            }\n }': AUTHOR_RESULT;
    '*[_type == \'ourStory\'\n  && defined(slug.current)]\n  |order(year)\n{\n  _id,\n  name,\n  "slug": slug.current,\n  year,\n  "titleEn": coalesce(title.en, \'\'),\n  "titleKo": coalesce(title.ko, \'\'),\n  "bodyEn": coalesce(body.en, \'\'),\n  "bodyKo": coalesce(body.ko, \'\'),\n }': ALL_STORIES_QUERY_RESULT;
    '*[_type == \'ourStory\'\n  && slug.current == $slug][0]{\n  _id,\n  name,\n  "slug": slug.current,\n  year,\n  "titleEn": coalesce(title.en, \'\'),\n  "titleKo": coalesce(title.ko, \'\'),\n  "bodyEn": coalesce(body.en, \'\'),\n  "bodyKo": coalesce(body.ko, \'\'),\n }': STORY_QUERY_RESULT;
  }
}
